version: '3.4'

services:
  cashflow.api:
    image: ${DOCKER_REGISTRY-}cashflowapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - cashflow.db
  cashflow.db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cashflow
    ports:
        - "3306:3306"