name: CD

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Generate tag
      id: tag
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: cashflowproduction.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
      
    - name: Build Docker images
      run: |
        docker build . -t cashflowproduction.azurecr.io/cashflowapi:${{ steps.tag.outputs.sha }} -t cashflowproduction.azurecr.io/cashflowapi:latest
      
    - name: Push Docker images
      run: |
        docker push cashflowproduction.azurecr.io/cashflowapi:${{ steps.tag.outputs.sha }}
        docker push cashflowproduction.azurecr.io/cashflowapi:latest
