# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore CashFlow.sln
    - name: Build
      run: dotnet build CashFlow.sln --configuration Release --no-restore
    - name: Run tests
      run: dotnet test CashFlow.sln --configuration Release --no-build --verbosity normal
    - name: Generate tag
      id: tag
      run: |
       SHA=$(echo $GITHUB_SHA | head -c7)
       echo "sha=$SHA" >> $GITHUB_OUTPUT
    - name: login into the container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build Docker image and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: guiduzera/cashflowapi:${{ steps.tag.outputs.sha }},guiduzera/cashflowapi:latest