# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore API dependencies
      run: dotnet restore CashFlow
    - name: Build
      run: dotnet build --no-restore --configuration Release CashFlow
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal CashFlow
