# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/CashFlow.API/CashFlow.API.csproj
    - name: Build
      run: dotnet build --no-restore --configuration Release src/CashFlow.API/CashFlow.API.csproj
    - name: Publish
      run: dotnet publish --no-build --configuration Release src/CashFlow.API/CashFlow.API.csproj -o out
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal tests/Validators.Tests/Validators.Tests.csproj
